#!/usr/bin/env bash
# Configure an Nginx server to listen to port 80

# Remove the Ngnix configuration file
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#Restart nginx
service nginx restart
