#!/usr/bin/env bash
# Configure an Nginx server to listen to port 80.

# Create symbolic link between nginx configuration file
# and the enabled site directory.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx.
service nginx restart
# Terminates the first ngninx process ID.
kill "$(pgrep 'nginx' | head -1)"
